"""baseline schema

The schema as it stood when migrations were introduced. A database created
before then (by the old create_all startup) is adopted at this revision by
app/db.py migrate() instead of running this. The kiosk's database was checked
column-for-column against it before that happened.

Revision ID: 851ee972b24c
Revises: 
Create Date: 2026-09-23 21:43:41.852851
"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # noqa: F401  autogenerate renders SQLModel's string type as sqlmodel.sql.sqltypes.AutoString
from alembic import op


revision: str = '851ee972b24c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('person_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('caldav_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('encrypted_credential', sa.LargeBinary(), nullable=True),
    sa.Column('oauth_refresh_token', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_selected_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_last_selected_at'), ['last_selected_at'], unique=False)

    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ingredients', sa.JSON(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('dietary_tags', sa.JSON(), nullable=True),
    sa.Column('allergens', sa.JSON(), nullable=True),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prep_time_minutes', sa.Integer(), nullable=True),
    sa.Column('cook_time_minutes', sa.Integer(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('ring_started_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('paused_remaining_seconds', sa.Float(), nullable=True),
    sa.Column('alarm_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('repeat', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('elapsed_seconds', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('rrule', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recurrence_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=False),
    sa.Column('reminder_lead_days', sa.Integer(), nullable=True),
    sa.Column('reminder_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reminder_dismissed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_uid'), ['uid'], unique=False)

    op.create_table('mealplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mealplan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mealplan_plan_date'), ['plan_date'], unique=True)

    op.create_table('recipefavorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('person_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipefavorite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipefavorite_person_name'), ['person_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipefavorite_recipe_id'), ['recipe_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipefavorite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipefavorite_recipe_id'))
        batch_op.drop_index(batch_op.f('ix_recipefavorite_person_name'))

    op.drop_table('recipefavorite')
    with op.batch_alter_table('mealplan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mealplan_plan_date'))

    op.drop_table('mealplan')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_uid'))
        batch_op.drop_index(batch_op.f('ix_event_start_time'))
        batch_op.drop_index(batch_op.f('ix_event_start_date'))
        batch_op.drop_index(batch_op.f('ix_event_end_time'))
        batch_op.drop_index(batch_op.f('ix_event_end_date'))
        batch_op.drop_index(batch_op.f('ix_event_account_id'))

    op.drop_table('event')
    op.drop_table('timer')
    op.drop_table('recipe')
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_last_selected_at'))

    op.drop_table('location')
    op.drop_table('account')
    # ### end Alembic commands ###
