"""add shopping list

Revision ID: 0afaeb8559fe
Revises: 1b3fe1eb0fe1
Create Date: 2026-09-28 20:50:51.764460
"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # noqa: F401  autogenerate renders SQLModel's string type as sqlmodel.sql.sqltypes.AutoString
from alembic import op


revision: str = '0afaeb8559fe'
down_revision: Union[str, Sequence[str], None] = '1b3fe1eb0fe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shoppingitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('manual', sa.Boolean(), nullable=False),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'week_start')
    )
    with op.batch_alter_table('shoppingitem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shoppingitem_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_shoppingitem_week_start'), ['week_start'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoppingitem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shoppingitem_week_start'))
        batch_op.drop_index(batch_op.f('ix_shoppingitem_key'))

    op.drop_table('shoppingitem')
    # ### end Alembic commands ###
